name = "tech-hilfe-pro-nrw"
compatibility_date = "2025-10-07"
pages_build_output_dir = ".vercel/output/static"

[env.production]
name = "tech-hilfe-pro-nrw"

[env.preview]
name = "tech-hilfe-pro-nrw-preview"
